version: "3"
services:
  bitwarden:
    container_name: bitwarden
    restart: always
    image: bitwardenrs/server:latest
    volumes:
      - bitwarden:/data
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bitwarden-ui.rule=Host(`bitwarden.localhost`)"
      - "traefik.http.routers.bitwarden-ui.service=bitwarden-ui"
      - "traefik.http.routers.bitwarden-ui.entrypoints=websecure"
      #- "traefik.http.routers.bitwarden-ui.tls.certresolver=mydnschallenge"
      - "traefik.http.services.bitwarden-ui.loadbalancer.server.port=80"
      - "traefik.http.routers.bitwarden-websocket.rule=Host(`bitwarden.localhost`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwarden-websocket.entrypoints=websecure"
      - "traefik.http.routers.bitwarden-websocket.service=bitwarden-websocket"
      #- "traefik.http.routers.bitwarden-websocket.tls.certresolver=mydnschallenge"
      - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012"

volumes:
  bitwarden:

networks:
  backend: