version: '3'

services:
  traefik:
    image: traefik:${IMAGE_VERSION}
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - edge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- traefik_data:/traefik_data
    container_name: traefik
networks:
  edge: